<a href="https://colab.research.google.com/github/NaveenManepalli/Machine-learning/blob/main/9NumPy_Numerical_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NumPy - Numerical Python**

Advantages of Numpy Arrays:

1. Allows several Mathematical Operations
2. Faster operations

In [1]:
import numpy as np

**List vs Numpy - Time Taken**

In [2]:
from time import process_time

In [21]:
python_list = [i for i in range(10000)]
start_time = process_time()
python_list=[i+5 for i in python_list]
end_time = process_time()
print(end_time-start_time)

0.0012245049999997093


In [20]:
np_array = np.array([i for i in  range (10000)])
start = process_time()
np_array +=5
end = process_time()
print(end-start)

0.00018753299999829665


**NumPy Arrays**

In [24]:
#list
list1 =[1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [25]:
np_array =np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [26]:
#creating a one dimension array
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [27]:
a.shape

(4,)

In [30]:
#creating 2 dimension
b=np.array([(1,2,3,4),(4,3,2,1)])
print(b)
b.shape

[[1 2 3 4]
 [4 3 2 1]]


(2, 4)

In [32]:
c=np.array([(1,2,3),(5,6,7)],dtype=float)
print(c)

[[1. 2. 3.]
 [5. 6. 7.]]


**Intitial place holders in numpy array**

In [33]:
#create a numpy arrays of 0 (zeros)
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [35]:
#create a numpy arrrays of 1 (ones)
y=np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [37]:
#create a numpy arrays for a unique number
z=np.full((4,4),7)
print(z)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [38]:
#create an identity matrix
a=np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [44]:
#create a numpy array with random values
bp=np.random.random((3,4))
print(bp)

[[0.26577481 0.31611985 0.87964187 0.7769368 ]
 [0.62181213 0.23387991 0.23947654 0.11966682]
 [0.68103728 0.5019883  0.15212026 0.61277533]]


In [42]:
#random integer value array with in a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[52 60 53 39 91]
 [82 57 15 90 38]
 [87 51 67 36 23]]


In [52]:
#arrays of evenly spaced values --> specifying eh number of values required
d = np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [53]:
#arrays of evnly spaced value --> specifing the step
e = np.arange(10,30,7)
print(e)

[10 17 24]


In [55]:
#convert a list to a numpy array
list2 = [10,20,30,40,50]

np_array2 = np.asarray(list2)
print(np_array2)
type(np_array2)

[10 20 30 40 50]


numpy.ndarray

**Analysing a numpy array**

In [57]:
cb = np.random.randint(10,90,(5,5))
print(cb)

[[38 10 51 38 12]
 [10 56 45 42 33]
 [64 65 72 73 13]
 [41 35 70 32 60]
 [36 70 53 23 59]]


In [60]:
#array dimension
print(cb.shape)

(5, 5)


In [62]:
#number of dimension
print(cb.ndim)

2


In [63]:
#Number of elements in an array
print(cb.size)

25


In [65]:
#Checking the datatype present in the value of array
print(c.dtype)

int64


**Mathematical operation present on the np array or NUM py Array**

In [66]:
list1 =[1,2,4,3]
list2 =[5,6,7,8]

print(list1+list2)

[1, 2, 4, 3, 5, 6, 7, 8]


In [68]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[1 3 2]
 [0 9 6]
 [9 8 5]]
[[16 15 11]
 [13 12 18]
 [14 11 15]]


In [69]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)

[[17 18 13]
 [13 21 24]
 [23 19 20]]
[[-15 -12  -9]
 [-13  -3 -12]
 [ -5  -3 -10]]
[[ 16  45  22]
 [  0 108 108]
 [126  88  75]]
[[0.0625     0.2        0.18181818]
 [0.         0.75       0.33333333]
 [0.64285714 0.72727273 0.33333333]]
[[1 3 2]
 [0 9 6]
 [9 8 5]]


In [70]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[8 2 2]
 [6 7 9]
 [2 3 4]]
[[10 16 15]
 [18 19 18]
 [18 15 18]]


In [72]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))


[[18 18 17]
 [24 26 27]
 [20 18 22]]
[[ -2 -14 -13]
 [-12 -12  -9]
 [-16 -12 -14]]
[[ 80  32  30]
 [108 133 162]
 [ 36  45  72]]
[[0.8        0.125      0.13333333]
 [0.33333333 0.36842105 0.5       ]
 [0.11111111 0.2        0.22222222]]


**Array Manipulation**

In [74]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[0 6 2]
 [1 0 1]]
(2, 3)


In [76]:
#transpose of the matrix
trans = np.transpose(array)
print(trans)
print(array.shape)

[[0 1]
 [6 0]
 [2 1]]
(2, 3)


In [77]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[2 9 5]
 [3 3 3]]
(2, 3)


In [78]:
#Another method of transpose
trans2 = array.T
print(trans2)
print(trans2.shape)

[[2 3]
 [9 3]
 [5 3]]
(3, 2)


In [79]:
#reshaping an array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[1 6 4]
 [3 7 2]]
(2, 3)


In [80]:
b= a.reshape(3,2)
print(b)
print(b.shape)

[[1 6]
 [4 3]
 [7 2]]
(3, 2)
